### ISSUE TITLE
node server/server.js fails on windows 10

### ISSUE THREAD

**Issue by HansS** [creationix/howtonode.org#117]
Hans@HP-HANS C:\Users\Hans\Web\bootcamps\hsr\cas-fee-2016\howtonode.org-wheat-blog-engine
> git branch
* master

Hans@HP-HANS C:\Users\Hans\Web\bootcamps\hsr\cas-fee-2016\howtonode.org-wheat-blog-engine
> node server/server.js
module.js:341
    throw err;
    ^

Error: Cannot find module 'creationix'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\Hans\Web\bootcamps\hsr\cas-fee-2016\howtonode.org-wheat-blog-engine\server\server.js:3:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by creationix** [comment]
Did you run `npm install` to get the dependencies?

**Comment by HansS** [comment]
Hi Tim,thank's for the message!
yes i did run: npm i
regardsHans

Date: Mon, 16 May 2016 13:34:12 -0700
